<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AMICHAITO1-HHS" ignored="1" name="Test-class test 9 redFinalOffer2" tests="12" failures="9" timestamp="28 Oct 2019 13:35:09 GMT" time="288.054" errors="0">
  <testcase name="initialOfferQuestions" time="18.249" classname="TestNG.sanityAllOptionsTest"/>
  <testcase name="callMeWizard1" time="13.032" classname="TestNG.sanityAllOptionsTest"/>
  <testcase name="initialOfferScreen" time="20.444" classname="TestNG.sanityAllOptionsTest"/>
  <testcase name="finalOfferQuestions" time="62.099" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in FINAL OFFER QUESTIONS">
      <![CDATA[java.lang.Exception: Failed in FINAL OFFER QUESTIONS
at TestNG.sanityAllOptionsTest.finalOfferQuestions(sanityAllOptionsTest.java:671)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- finalOfferQuestions -->
  <testcase name="finalOfferScreen" time="30.341" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in FINAL OFFER screen">
      <![CDATA[java.lang.Exception: Failed in FINAL OFFER screen
at TestNG.sanityAllOptionsTest.finalOfferScreen(sanityAllOptionsTest.java:732)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- finalOfferScreen -->
  <testcase name="covers" time="30.437" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in COVERS screen">
      <![CDATA[java.lang.Exception: Failed in COVERS screen
at TestNG.sanityAllOptionsTest.covers(sanityAllOptionsTest.java:815)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- covers -->
  <testcase name="payments" time="31.515" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in PAYMENTS screen">
      <![CDATA[java.lang.Exception: Failed in PAYMENTS screen
at TestNG.sanityAllOptionsTest.payments(sanityAllOptionsTest.java:865)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- payments -->
  <testcase name="returnSteps" time="0.023" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in moveing BACKWARD">
      <![CDATA[java.lang.Exception: Failed in moveing BACKWARD
at TestNG.sanityAllOptionsTest.returnSteps(sanityAllOptionsTest.java:990)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- returnSteps -->
  <testcase name="forwardSteps" time="2.032" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in moveing FORWARD">
      <![CDATA[java.lang.Exception: Failed in moveing FORWARD
at TestNG.sanityAllOptionsTest.forwardSteps(sanityAllOptionsTest.java:1089)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- forwardSteps -->
  <testcase name="iframeCreditGuard" time="40.399" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed in Iframe CreditGuard">
      <![CDATA[java.lang.Exception: Failed in Iframe CreditGuard
at TestNG.sanityAllOptionsTest.iframeCreditGuard(sanityAllOptionsTest.java:1136)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- iframeCreditGuard -->
  <testcase name="thankYouPage" time="35.391" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed to display thank you page">
      <![CDATA[java.lang.Exception: Failed to display thank you page
at TestNG.sanityAllOptionsTest.thankYouPage(sanityAllOptionsTest.java:1153)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- thankYouPage -->
  <testcase name="registeredAccount" time="4.047" classname="TestNG.sanityAllOptionsTest">
    <failure type="java.lang.Exception" message="Failed to display thank you page">
      <![CDATA[java.lang.Exception: Failed to display thank you page
at TestNG.sanityAllOptionsTest.registeredAccount(sanityAllOptionsTest.java:1174)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- registeredAccount -->
  <testcase name="callMeWizard2" time="0.0" classname="TestNG.sanityAllOptionsTest">
    <ignored/>
  </testcase> <!-- callMeWizard2 -->
</testsuite> <!-- Test-class test 9 redFinalOffer2 -->
